Fix TravisCI failure, don't generate .ino file, only .cpp
With ino version 0.3.6 and newer this caused build failures (see below).
For some reason, in the preprocessed .cpp file, the graph declaration was after
its usage, and output indicated it came from "firmware.ino", when it is also in firmware.cpp.

src/firmware.cpp
In file included from lib/microflo/microflo.hpp:11:0,
from .build/uno/src/serial.cpp:3:
lib/microflo/main.hpp: In function ‘void setup()’:
lib/microflo/main.hpp:20:28: error: ‘graph’ was not declared in this scope
make[1]: *** [.build/uno/src/serial.o] Error 1